name: Get daily stats
on:
  schedule:
    - cron: "0 19 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:

    - name: Git clone
      uses: actions/checkout@v2
      with:
        persist-credentials: false 
        fetch-depth: 0

    - name: Fetch
      env:
        PAT: ${{ secrets.PAT }}
      shell: bash
      run: |
        export FILENAME=$(./utils/today.sh)
        # Fetch
        curl https://raw.githubusercontent.com/cncf/landscape/master/landscape.yml --header "Authorization: Bearer $PAT" > landscape.yaml
        
        # Extract
        ./create-repo-list.sh landscape.yaml unsorted-$FILENAME
        
        # Archive
        sort -nr unsorted-$FILENAME > archive/$FILENAME
        
        # Cleanup
        rm unsorted-$FILENAME
        rm landscape.yaml

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: GitHub Commit & Push
      uses: actions-js/push@v1.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.extract_branch.outputs.branch }}
